# Generated by Django 6.0.6 on 2026-06-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('distancia_km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('servicios', models.CharField(max_length=160)),
                ('precio_93', models.IntegerField(default=1149)),
                ('distancia_km', models.FloatField(default=1.0)),
                ('destacada', models.BooleanField(default=False, verbose_name='Mejor precio')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('detalle', models.CharField(max_length=120)),
                ('progreso', models.IntegerField(default=0, verbose_name='Progreso (%)')),
            ],
            options={
                'verbose_name_plural': 'Misiones Full',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Joaquín', max_length=60)),
                ('saldo_copec_pay', models.IntegerField(default=48200)),
                ('puntos_full', models.IntegerField(default=12540)),
                ('nivel', models.CharField(default='Full Oro', max_length=30)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=80)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EstacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('km_punto', models.IntegerField()),
                ('servicios', models.CharField(max_length=120)),
                ('orden', models.IntegerField(default=0)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones_ruta', to='superapp.destino')),
            ],
            options={
                'verbose_name_plural': 'Estaciones en ruta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Toyota', max_length=40)),
                ('modelo', models.CharField(default='RAV4', max_length=40)),
                ('anio', models.IntegerField(default=2022)),
                ('motor', models.CharField(default='2.0L', max_length=20)),
                ('traccion', models.CharField(default='4x4', max_length=20)),
                ('combustible', models.CharField(default='Gasolina', max_length=20)),
                ('patente', models.CharField(default='KJ·PR·45', max_length=10)),
                ('kilometraje', models.IntegerField(default=42760)),
                ('rendimiento_kml', models.FloatField(default=13.2, verbose_name='Rendimiento (km/L)')),
                ('aceite_actual', models.CharField(default='Mobil 1 5W-30 sintético (10.02.2025)', max_length=80)),
                ('presion_del', models.IntegerField(default=33, verbose_name='Presión delantera (psi)')),
                ('presion_tra', models.IntegerField(default=32, verbose_name='Presión trasera (psi)')),
                ('km_prox_mantencion', models.IntegerField(default=1240)),
                ('prox_servicio', models.CharField(default='Cambio de aceite', max_length=60)),
                ('medida_neumatico', models.CharField(default='225/65 R17', max_length=20)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='superapp.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('detalle', models.CharField(max_length=120)),
                ('color', models.CharField(choices=[('orange', 'Naranjo'), ('blue', 'Azul'), ('green', 'Verde'), ('navy', 'Azul marino')], default='blue', max_length=10)),
                ('orden', models.IntegerField(default=0)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones', to='superapp.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Mantenciones / historial',
                'ordering': ['orden'],
            },
        ),
    ]
