# Generated by Django 6.0.6 on 2026-06-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superapp", "0002_seed_demo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("carga", "Carga"), ("pronto", "Pronto"), ("lavado", "Lavado"), ("mantencion", "Mantención"), ("carga_electrica", "Carga eléctrica")], max_length=20)),
                ("descripcion", models.CharField(max_length=120)),
                ("monto", models.IntegerField(default=0)),
                ("puntos_ganados", models.IntegerField(default=0)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("perfil", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transacciones", to="superapp.perfilusuario")),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
    ]