# Generated by Django 6.0.6 on 2026-06-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superapp", "0004_seed_transacciones"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("vehiculo", "Vehículo"), ("promo", "Promo"), ("mision", "Misión"), ("carga", "Carga"), ("sistema", "Sistema")], max_length=20)),
                ("titulo", models.CharField(max_length=120)),
                ("detalle", models.CharField(max_length=180)),
                ("icono", models.CharField(blank=True, max_length=40, null=True)),
                ("leida", models.BooleanField(default=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("perfil", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notificaciones", to="superapp.perfilusuario")),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
    ]