# Generated by Django 6.0.6 on 2026-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superapp", "0006_seed_notificaciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="capacidad_estanque_l",
            field=models.IntegerField(default=55),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="nivel_combustible",
            field=models.IntegerField(default=50),
        ),
    ]