# Generated by Django 6.0.6 on 2026-06-05 14:30

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superapp", "0008_seed_vehicle_fuel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="nivel_combustible",
            field=models.IntegerField(default=50, validators=[MinValueValidator(0), MaxValueValidator(100)]),
        ),
    ]