# Generated by Django 6.0.6 on 2026-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superapp", "0009_alter_vehiculo_nivel_combustible"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="cupo_combustible",
            field=models.IntegerField(default=90000),
        ),
    ]